apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  storageClassName: manual
  accessModes:
    #the accessMode: here --> can be used by a single node
    - ReadWriteOnce
  resources:
    requests:
      # 2 GB storage
      storage: 2Gi