apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
  annotations:
    volume.alpha.kubernetes.io/storage-class: defaul
spec:
  storageClassName: manual
  accessModes:
    #the accessMode: here --> can be used by a single node
    - ReadWriteOnce
  resources:
    requests:
      # 2 GB storage
      storage: 1Gi